import { visibleRows } from "@/lib/visibility";

import { AppError,currentUser,requireUser,sameOrigin,setting,database,config,saveConfig,hashPassword,verifyPassword,sessionCookie,sign,limit,validText,random,seal,unseal,cookie } from "@/lib/security";
import { TABLES,COMMON,ROOT_FOLDER,Row,YEARS } from "@/lib/a14-schema";
import { accessToken,gapi,initializeDrive,storage,rows,append,update,newRow,audit,folder,oauthRedirect } from "@/lib/google";
export const dynamic="force-dynamic";
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff",...headers}});
const clean=(r:Row)=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=="_row"));
const active=(r:Row)=>r.status!=="deleted";
async function record(table:string,id:string){const r=(await rows(table)).find(r=>r.id===id&&active(r));if(!r)throw new AppError(404,"Nội dung không còn tồn tại.");return r}
async function target(type:string,id:string){if(!["BAI_VIET","TEP_MEDIA"].includes(type))throw new AppError(400,"Nội dung liên kết không hợp lệ.");return record(type,id)}
function validate(table:string,input:any){const out:Row={};for(const field of TABLES[table].fields){if(input[field]!==undefined)out[field]=validText(String(input[field]),field,field==="content"?12000:field==="bio"||field==="description"?2000:500,false)}
const required:Record<string,string[]>={ALBUM:["title","year"],BAI_VIET:["title","content"],HO_SO:["name"],BINH_LUAN:["target_type","target_id","content"],CAM_XUC:["target_type","target_id"],SU_KIEN:["title"],PHUONG_AN_HOP_LOP:["event_id","label"],BINH_CHON:["event_id","option_id"],THAM_GIA:["event_id","answer"],AM_NHAC:["title","url"],LUU_BUT:["recipient_id","content"],THU_THOI_GIAN:["recipient_id","content","opens_at"],BAO_CAO:["target_type","target_id","content"]};
for(const f of required[table]||[])if(!out[f])throw new AppError(400,"Vui lòng điền đầy đủ thông tin.");
if(out.year&&!YEARS.includes(out.year))throw new AppError(400,"Năm học không hợp lệ.");
if(table==="AM_NHAC"){let url:URL;try{url=new URL(out.url)}catch{throw new AppError(400,"Liên kết bài hát không hợp lệ.")}if(url.protocol!=="https:")throw new AppError(400,"Liên kết bài hát cần bắt đầu bằng https://");}
if(table==="HO_SO"&&out.seat&&!/^([1-9]|1[0-9]|2[0-4])-[12]$/.test(out.seat))throw new AppError(400,"Chỗ ngồi không hợp lệ.");
if(["LUU_BUT","THU_THOI_GIAN"].includes(table)){if(!["private","class"].includes(out.visibility||""))throw new AppError(400,"Hãy chọn quyền xem.");if(table==="THU_THOI_GIAN"&&(!Number.isFinite(Date.parse(out.opens_at))||Date.parse(out.opens_at)<=Date.now()))throw new AppError(400,"Ngày mở thư phải ở tương lai.");}
if(table==="THAM_GIA"){if(!["yes","maybe","no"].includes(out.answer))throw new AppError(400,"Lựa chọn không hợp lệ.");if(!/^[0-9]$/.test(out.guests||"0"))throw new AppError(400,"Số người đi cùng từ 0 đến 9.");}
if(table==="SU_KIEN"&&out.date&&!Number.isFinite(Date.parse(out.date)))throw new AppError(400,"Ngày sự kiện không hợp lệ.");
return out}
async function log(u:string,action:string,id:string){try{await audit(u,action,id)}catch{console.error("A14 audit write unavailable")}}
async function get(req:Request,p:string[]){
if(p.join("/")==="me"){const user=await currentUser(req);let connected=false,initialized=false;if(user){connected=!!(await config("google"))?.refresh_token;initialized=!!await config("storage");}return json({user,connected,initialized});}
if(p.join("/")==="admin/status"){await requireUser(req,true);const g=await config("google");const s=await config("storage");return json({configured:!!g?.client_id,connected:!!g?.refresh_token,initialized:!!s,root:ROOT_FOLDER,redirect_uri:oauthRedirect(),content:s?.content||null,privateSheet:s?.privateSheet||null});}
if(p.join("/")==="admin/users"){await requireUser(req,true);return json({rows:(await database().prepare("SELECT id,username,name,email,status,created_at FROM auth_users ORDER BY created_at DESC").all()).results});}
if(p.join("/")==="google/callback"){const url=new URL(req.url);const state=url.searchParams.get("state");if(!state)throw new AppError(403,"Phiên kết nối Google không hợp lệ. Hãy bắt đầu lại.");const st=await database().prepare("DELETE FROM oauth_states WHERE id=? RETURNING verifier,expires").bind(state).first<{verifier:string;expires:number}>();if(!st||st.expires<Date.now())throw new AppError(403,"Phiên kết nối đã hết hạn.");const returnUrl=setting("FRONTEND_URL")||setting("SITE_ORIGIN")+"/";if(url.searchParams.has("error"))return Response.redirect(returnUrl+"#/lop?view=admin&google=cancelled",303);const c=await config("google");const verifier=await unseal(st.verifier);const res=await fetch("https://oauth2.googleapis.com/token",{method:"POST",body:new URLSearchParams({code:url.searchParams.get("code")||"",client_id:c.client_id,client_secret:c.client_secret,redirect_uri:oauthRedirect(),grant_type:"authorization_code",code_verifier:verifier})});const data=await res.json() as any;if(!res.ok||!data.refresh_token)throw new AppError(400,"Google chưa cấp quyền lưu trữ lâu dài. Hãy kết nối lại và đồng ý các quyền cần thiết.");await saveConfig("google",{...c,refresh_token:data.refresh_token,access_token:data.access_token,expires:Date.now()+data.expires_in*1000});return Response.redirect(returnUrl+"#/lop?view=admin&google=connected",303);}
if(p[0]==="data"&&p[1]){const user=await requireUser(req);const table=p[1];if(!TABLES[table])throw new AppError(404,"Không có bảng này.");if(["TAI_KHOAN","YEU_CAU_THAM_GIA","NHAT_KY"].includes(table)&&user.role!=="admin")throw new AppError(403,"Bạn không có quyền xem dữ liệu này.");const data=visibleRows(table,await rows(table),user);return json({rows:data.map(clean)});}
if(p[0]==="media"&&p[1]){await requireUser(req);const row=await record("TEP_MEDIA",p[1]);const response=await fetch("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(row.drive_file_id)+"?alt=media",{headers:{Authorization:"Bearer "+await accessToken()}});if(!response.ok)throw new AppError(502,"Chưa tải được ảnh. Vui lòng thử lại.");return new Response(response.body,{headers:{"Content-Type":row.mime_type,"Content-Disposition":"inline; filename*=UTF-8''"+encodeURIComponent(row.file_name),"Cache-Control":"private, max-age=300","X-Content-Type-Options":"nosniff"}});}
throw new AppError(404,"Không tìm thấy chức năng.")}
async function post(req:Request,p:string[]){
sameOrigin(req);
if(p.join("/")==="auth/login"){await limit(req,"login");const b:any=await req.json();const username=validText(b.username,"Tên đăng nhập",40).toUpperCase();const password=validText(b.password,"Mật khẩu",200);let user:any;if(username===(setting("ADMIN_USERNAME")||"TANNV")){if(await verifyPassword(password,setting("ADMIN_PASSWORD_HASH")))user={id:"admin",status:"active"}}else{const u=await database().prepare("SELECT id,password_hash,status FROM auth_users WHERE username=?").bind(username).first<any>();const valid=await verifyPassword(password,u?.password_hash||setting("ADMIN_PASSWORD_HASH"));if(u&&valid)user=u}if(!user)throw new AppError(401,"Tên đăng nhập hoặc mật khẩu chưa đúng.");if(user.status!=="active")throw new AppError(403,user.status==="pending"?"Tài khoản đang chờ quản trị viên duyệt.":"Tài khoản đã bị khóa.");const token=await sign({purpose:"session",id:user.id,exp:Date.now()+28800000});const crossOrigin=req.headers.get("origin")===setting("FRONTEND_ORIGIN");return json({ok:true,...(crossOrigin?{token}:{})},200,{"Set-Cookie":sessionCookie(req,token)});}
if(p.join("/")==="auth/logout")return json({ok:true},200,{"Set-Cookie":sessionCookie(req,"",0)});
if(p.join("/")==="auth/register"){await limit(req,"register",5);const b:any=await req.json();const username=validText(b.username,"Tên đăng nhập",40).toUpperCase();if(!/^[A-Z0-9_]{3,40}$/.test(username)||username===(setting("ADMIN_USERNAME")||"TANNV"))throw new AppError(400,"Tên đăng nhập gồm 3–40 chữ không dấu, số hoặc dấu gạch dưới.");const password=validText(b.password,"Mật khẩu",200);if(password.length<10)throw new AppError(400,"Mật khẩu cần ít nhất 10 ký tự.");const name=validText(b.name,"Họ tên",100);const email=validText(b.email||"","Email",150,false);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError(400,"Email không hợp lệ.");if(await database().prepare("SELECT id FROM auth_users WHERE username=?").bind(username).first())throw new AppError(409,"Tên đăng nhập này đã được sử dụng.");const id=crypto.randomUUID();try{await database().prepare("INSERT INTO auth_users(id,username,name,email,password_hash,status,created_at) VALUES(?,?,?,?,?,'pending',?)").bind(id,username,name,email,await hashPassword(password),new Date().toISOString()).run()}catch{throw new AppError(409,"Chưa tạo được tài khoản; tên đăng nhập có thể đã được sử dụng.");}return json({ok:true,message:"Đã gửi yêu cầu. Bạn có thể đăng nhập sau khi quản trị viên duyệt."},201);}
const user=await requireUser(req);
if(p.join("/")==="admin/google-config"){await requireUser(req,true);const b:any=await req.json();const client_id=validText(b.client_id,"Client ID",300);if(!client_id.endsWith(".apps.googleusercontent.com"))throw new AppError(400,"Google Client ID không hợp lệ.");const client_secret=validText(b.client_secret,"Client secret",300);await saveConfig("google",{client_id,client_secret});return json({ok:true});}
if(p.join("/")==="google/connect"){await requireUser(req,true);const c=await config("google");if(!c?.client_id)throw new AppError(400,"Vui lòng lưu Client ID và Client secret trước.");const state=random(),verifier=random();await database().prepare("INSERT INTO oauth_states(id,verifier,expires) VALUES(?,?,?)").bind(state,await seal(verifier),Date.now()+600000).run();const challenge=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));const b64=btoa(String.fromCharCode(...new Uint8Array(challenge))).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"");const url="https://accounts.google.com/o/oauth2/v2/auth?"+new URLSearchParams({client_id:c.client_id,redirect_uri:oauthRedirect(),response_type:"code",scope:"https://www.googleapis.com/auth/drive",access_type:"offline",prompt:"consent",state,code_challenge:b64,code_challenge_method:"S256"});return json({url},200,{"Set-Cookie":"a14_oauth="+state+"; Path=/; HttpOnly; SameSite=Lax; Max-Age=600"+(new URL(req.url).protocol==="https:"?"; Secure":"")});}
if(p.join("/")==="google/init"){await requireUser(req,true);await limit(req,"initialize",4);const initialized=await initializeDrive();const existing=await rows("HO_SO");if(!existing.some(r=>r.member_id==="admin"))await append("HO_SO",newRow("admin",{member_id:"admin",name:"TANNV",nickname:"",bio:"",seat:""}));if(!(await rows("CAU_HINH_LOP")).some(active))await append("CAU_HINH_LOP",newRow("admin",{class_name:"A14",school:"",school_years:"",intro:"Ngày ấy, chúng ta từng ngồi đây."}));await log(user.id,"Khởi tạo kho kỷ niệm",ROOT_FOLDER);return json({ok:true,...initialized});}
if(p.join("/")==="admin/user"){await requireUser(req,true);const b:any=await req.json();if(!["active","pending","blocked"].includes(b.status))throw new AppError(400,"Trạng thái không hợp lệ.");const u=await database().prepare("SELECT id,username,name,email,status FROM auth_users WHERE id=?").bind(b.id).first<any>();if(!u)throw new AppError(404,"Không tìm thấy thành viên.");await storage();if(b.status==="active"){const profiles=await rows("HO_SO");if(!profiles.some(r=>r.member_id===u.id))await append("HO_SO",newRow(u.id,{member_id:u.id,name:u.name,nickname:"",bio:"",seat:""}));}
const accounts=await rows("TAI_KHOAN");const old=accounts.find(r=>r.member_id===u.id);const fields={member_id:u.id,username:u.username,name:u.name,email:u.email,role:"member",account_status:b.status};if(old)await update("TAI_KHOAN",{...old,...fields,updated_at:new Date().toISOString()});else await append("TAI_KHOAN",newRow(user.id,fields));await database().prepare("UPDATE auth_users SET status=? WHERE id=?").bind(b.status,b.id).run();await log(user.id,"Đổi trạng thái tài khoản: "+b.status,u.id);return json({ok:true});}
if(p[0]==="data"&&p[1]){const table=p[1];if(!TABLES[table]||["TEP_MEDIA","TAI_KHOAN","YEU_CAU_THAM_GIA","NHAT_KY","GAN_THE","BAI_VIET_MEDIA"].includes(table))throw new AppError(403,"Không thể tạo dữ liệu tại bảng này.");if(table==="CAU_HINH_LOP"&&user.role!=="admin")throw new AppError(403,"Chỉ quản trị viên được sửa thông tin lớp.");const b:any=await req.json();const fields=validate(table,b);let old:Row|undefined;
if(["BINH_LUAN","CAM_XUC","BAO_CAO"].includes(table))await target(fields.target_type,fields.target_id);
if(["LUU_BUT","THU_THOI_GIAN"].includes(table)&&!(await rows("HO_SO")).some(r=>r.member_id===fields.recipient_id&&active(r)))throw new AppError(400,"Người nhận không có trong lớp.");
if(["PHUONG_AN_HOP_LOP","BINH_CHON","THAM_GIA"].includes(table)){await record("SU_KIEN",fields.event_id);if(table==="PHUONG_AN_HOP_LOP"){const event=await record("SU_KIEN",fields.event_id);if(user.role!=="admin"&&event.owner_id!==user.id)throw new AppError(403,"Chỉ người tạo sự kiện được thêm phương án.");}if(table==="BINH_CHON"){const option=await record("PHUONG_AN_HOP_LOP",fields.option_id);if(option.event_id!==fields.event_id)throw new AppError(400,"Phương án không thuộc sự kiện.");}}
if(["HO_SO","CAM_XUC","BINH_CHON","THAM_GIA","CAU_HINH_LOP"].includes(table)){const existing=await rows(table);old=existing.find(r=>active(r)&&(table==="CAU_HINH_LOP"||(r.owner_id===user.id&&(table==="HO_SO"||(table==="CAM_XUC"?r.target_id===fields.target_id&&r.target_type===fields.target_type:r.event_id===fields.event_id)))));if(table==="HO_SO"){fields.member_id=user.id;if(fields.seat&&existing.some(r=>active(r)&&r.owner_id!==user.id&&r.seat===fields.seat))throw new AppError(409,"Chỗ này đã có bạn nhận. Hãy chọn chỗ khác.");}}
if(table==="ALBUM"){const s=await storage();const map:Record<string,string>={"Lớp 10":"Lop_10","Lớp 11":"Lop_11","Lớp 12":"Lop_12","Họp lớp":"Hop_lop","Chưa rõ năm":"Chua_ro_nam"};fields.folder_id=await folder(s.yearFolders[map[fields.year]],fields.title+"-"+crypto.randomUUID().slice(0,8));}
if(table==="CAM_XUC")fields.kind="heart";
const row=old?{...old,...fields,updated_at:new Date().toISOString()}:newRow(user.id,fields);if(old)await update(table,row);else await append(table,row);return json({row:clean(row)},old?200:201);}
if(p[0]==="media"&&p.length===1){await limit(req,"upload",100);const length=Number(req.headers.get("content-length")||0);if(length>27*1024*1024)throw new AppError(413,"Mỗi tệp tối đa 25 MB.");const form=await req.formData();const file=form.get("file");if(!(file instanceof File)||!file.size||file.size>25*1024*1024)throw new AppError(400,"Chọn ảnh/video hợp lệ, tối đa 25 MB.");const album=await record("ALBUM",String(form.get("album_id")||""));const caption=validText(String(form.get("caption")||""),"Chú thích",2000,false);const bytes=new Uint8Array(await file.arrayBuffer());let mime="";if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime="image/jpeg";if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)mime="image/png";if(new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP")mime="image/webp";if(new TextDecoder().decode(bytes.slice(4,8))==="ftyp"&&["isom","iso2","mp41","mp42","avc1","M4V "].includes(new TextDecoder().decode(bytes.slice(8,12))))mime="video/mp4";if(!mime)throw new AppError(400,"Hỗ trợ JPG, PNG, WebP và video MP4. Hãy chuyển ảnh HEIC sang JPG trước khi đăng.");
const boundary="a14_"+random();const meta={name:file.name.slice(0,200),parents:[album.folder_id]};const upload=new Blob(["--"+boundary+"\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n"+JSON.stringify(meta)+"\r\n--"+boundary+"\r\nContent-Type: "+mime+"\r\n\r\n",bytes,"\r\n--"+boundary+"--"]);
const data=await gapi("upload/drive/v3/files?uploadType=multipart&fields=id",{method:"POST",headers:{"Content-Type":"multipart/related; boundary="+boundary},body:upload});try{const r=await append("TEP_MEDIA",newRow(user.id,{album_id:album.id,drive_file_id:data.id,file_name:file.name.slice(0,200),mime_type:mime,size:String(file.size),caption}));return json({row:clean(r)},201)}catch(e){try{await gapi("drive/v3/files/"+data.id,{method:"DELETE"})}catch{console.error("A14 upload needs cleanup")};throw e}}
throw new AppError(404,"Không tìm thấy chức năng.")}
async function patch(req:Request,p:string[]){sameOrigin(req);const user=await requireUser(req);if(p[0]!=="data"||!TABLES[p[1]])throw new AppError(404,"Không có bảng này.");const table=p[1];if(["TAI_KHOAN","YEU_CAU_THAM_GIA","NHAT_KY"].includes(table))throw new AppError(403,"Không được sửa bảng này.");const b:any=await req.json();const old=await record(table,validText(b.id,"Mã bản ghi",100));if(old.owner_id!==user.id&&user.role!=="admin")throw new AppError(403,"Bạn chỉ được sửa nội dung của mình.");if(["LUU_BUT","THU_THOI_GIAN"].includes(table)&&!b.remove)throw new AppError(400,"Thư đã gửi không thể sửa. Bạn có thể gỡ và viết lại.");let row:Row;
if(b.remove){row={...old,status:"deleted",updated_at:new Date().toISOString()};}
else if(table==="BAO_CAO"){if(user.role!=="admin")throw new AppError(403,"Chỉ quản trị viên được xử lý báo cáo.");row={...old,resolution:validText(b.resolution,"Kết quả xử lý",1000),updated_at:new Date().toISOString()};}
else if(table==="TEP_MEDIA"){row={...old,caption:validText(b.caption,"Chú thích",2000,false),updated_at:new Date().toISOString()};}
else{const fields=validate(table,{...old,...b});delete fields.folder_id;delete fields.member_id;row={...old,...fields,updated_at:new Date().toISOString()};}
if(b.remove&&table==="ALBUM"&&(await rows("TEP_MEDIA")).some(r=>active(r)&&r.album_id===old.id))throw new AppError(409,"Hãy gỡ ảnh/video trong album trước khi gỡ album.");
await update(table,row);await log(user.id,b.remove?"Gỡ "+table:"Cập nhật "+table,old.id);return json({row:clean(row)});}
async function handler(req:Request,context:{params:Promise<{path:string[]}>},fn:typeof get){try{return cors(req,await fn(req,(await context.params).path))}catch(error){if(error instanceof AppError)return cors(req,json({error:error.message},error.status));console.error("A14 request failed",error instanceof Error?error.name:"unknown");return cors(req,json({error:"Chưa thể hoàn tất thao tác. Dữ liệu bạn đang nhập vẫn được giữ; vui lòng thử lại."},500))}}
export const GET=(r:Request,c:any)=>handler(r,c,get);
export const POST=(r:Request,c:any)=>handler(r,c,post);
export const PATCH=(r:Request,c:any)=>handler(r,c,patch);

function cors(req:Request,response:Response){const origin=req.headers.get("origin");if(origin&&origin===setting("FRONTEND_ORIGIN")){const headers=new Headers(response.headers);headers.set("Access-Control-Allow-Origin",origin);headers.set("Access-Control-Allow-Credentials","true");headers.append("Vary","Origin");return new Response(response.body,{status:response.status,headers})}return response}
export async function OPTIONS(req:Request){const origin=req.headers.get("origin");if(!origin||origin!==setting("FRONTEND_ORIGIN"))return json({error:"Origin không được phép."},403);return new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Methods":"GET, POST, PATCH, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Max-Age":"600","Vary":"Origin"}})}
