
"use client";
import {apiFetch,goTo,routeHref,assetUrl} from "@/lib/browser-api";
import {useState} from "react";
import {ArrowLeft,ArrowRight,BookOpen,Eye,EyeOff,LoaderCircle} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
export default function Login(){const[mode,setMode]=useState("login");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setSuccess("");const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await apiFetch("auth/"+(mode==="login"?"login":"register"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const b:any=await r.json();if(!r.ok)throw new Error(b.error||"Chưa thể đăng nhập.");if(mode==="login"){if(b.token)sessionStorage.setItem("a14_session",b.token);goTo("/lop")}else{setSuccess(b.message);setMode("login")}}catch(err){setError(err instanceof Error?err.message:"Mất kết nối. Hãy thử lại.")}finally{setBusy(false)}}
return <main className="login-page"><section className="login-art"><img src={assetUrl("/classroom.webp")} alt="Lớp học trong nắng chiều, tranh minh họa"/><div className="login-art-copy"><a className="light-brand" href={routeHref("/")}><BookOpen/> A14 · Miền ký ức</a><blockquote>Thời gian đi qua.<br/>Kỷ niệm ở lại.</blockquote><p>Mình lại gặp nhau, ở lớp học năm ấy.</p></div></section><section className="login-panel"><a className="back" href={routeHref("/")}><ArrowLeft size={16}/> Về trang đầu</a><div className="login-card"><span className="eyebrow">CHÀO BẠN, NGƯỜI BẠN CŨ</span><h1>{mode==="login"?"Về lại lớp mình.":"Thêm một người bạn."}</h1><p className="muted">Đăng nhập để cùng góp và giữ những kỷ niệm của A14.</p><Tabs value={mode} onValueChange={v=>{setMode(v);setError("");setSuccess("")}}><TabsList className="login-tabs"><TabsTrigger value="login">Đăng nhập</TabsTrigger><TabsTrigger value="register">Xin tham gia lớp</TabsTrigger></TabsList></Tabs><form onSubmit={submit} className="form-stack">{mode==="register"&&<><label>Họ và tên<input name="name" required maxLength={100} autoComplete="name" placeholder="Tên để cả lớp nhận ra bạn"/></label><label>Email <span className="muted">(không bắt buộc)</span><input type="email" name="email" autoComplete="email" maxLength={150} placeholder="ban@example.com"/></label></>}<label>Tên đăng nhập<input name="username" required minLength={3} maxLength={40} autoComplete="username" placeholder="Tên đăng nhập của bạn" spellCheck={false} autoCapitalize="none"/></label><label>Mật khẩu<div className="password-field"><input name="password" type={show?"text":"password"} required minLength={mode==="register"?10:1} maxLength={200} autoComplete={mode==="register"?"new-password":"current-password"} placeholder={mode==="register"?"Ít nhất 10 ký tự":"Nhập mật khẩu"}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Ẩn mật khẩu":"Hiện mật khẩu"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="error-box" role="alert">{error}</div>}{success&&<div className="success-box" role="status">{success}</div>}<button className="primary wide" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:null}{mode==="login"?"Vào lớp mình":"Gửi yêu cầu tham gia"}<ArrowRight size={17}/></button>{mode==="register"&&<p className="field-hint">Quản trị viên sẽ xác nhận bạn là thành viên trước khi mở quyền xem và đăng kỷ niệm.</p>}</form><p className="login-foot">Không gian riêng của những người bạn A14.</p></div></section></main>}
