
import { AppError,config,saveConfig,setting } from "./security";
import { ROOT_FOLDER,TABLES,COMMON,Row } from "./a14-schema";
type GoogleConnection={client_id:string;client_secret:string;refresh_token?:string;access_token?:string;expires?:number};
const SCHEMA_VERSION=2;
let schemaUpgrade:Promise<any>|null=null;
export async function accessToken(){const c=await config("google") as GoogleConnection|null;if(!c?.refresh_token)throw new AppError(503,"Kho kỷ niệm chưa kết nối Google Drive. Quản trị viên cần hoàn tất kết nối trước khi lưu dữ liệu.");if(c.access_token&&(c.expires||0)>Date.now()+60000)return c.access_token;const res=await fetch("https://oauth2.googleapis.com/token",{method:"POST",body:new URLSearchParams({client_id:c.client_id,client_secret:c.client_secret,refresh_token:c.refresh_token,grant_type:"refresh_token"})});const data=await res.json() as any;if(!res.ok)throw new AppError(503,"Kết nối Google đã hết hiệu lực. Quản trị viên vui lòng kết nối lại.");await saveConfig("google",{...c,access_token:data.access_token,expires:Date.now()+data.expires_in*1000});return data.access_token as string}
export async function gapi(path:string,options:RequestInit={},token?:string):Promise<any>{const isSheets=path.startsWith("sheets/");const response=await fetch(isSheets?"https://sheets.googleapis.com/"+path.slice(7):"https://www.googleapis.com/"+path,{...options,headers:{Authorization:"Bearer "+(token||await accessToken()),...(options.body&&typeof options.body==="string"?{"Content-Type":"application/json"}:{}),...options.headers}});if(!response.ok){const failure:any=await response.clone().json().catch(()=>({}));const detail=failure?.error?.details?.find((item:any)=>item?.reason||item?.metadata?.service);const reason=detail?.reason||failure?.error?.errors?.[0]?.reason||"";const service=detail?.metadata?.service||(isSheets?"sheets.googleapis.com":"drive.googleapis.com");console.error("Google API request failed",{endpoint:path.split("?")[0],status:response.status,reason,service});if(response.status===429)throw new AppError(429,"Google đang giới hạn lượt truy cập. Vui lòng thử lại sau một lúc.");if(response.status===403&&isSheets)throw new AppError(503,"Google Sheets API đang bị từ chối trong project OAuth hiện tại. Hãy bật Google Sheets API trong đúng project chứa Client ID rồi thử lại.");if(response.status===403&&reason.includes("ACCESS_TOKEN_SCOPE"))throw new AppError(503,"Phiên Google đang thiếu quyền Drive. Hãy chọn Kết nối lại và chấp nhận đầy đủ quyền.");if(response.status===403)throw new AppError(503,"Tài khoản Google không có quyền chỉnh sửa kho A14 hoặc Google Drive API chưa được bật trong đúng project OAuth.");if(response.status===404)throw new AppError(404,"Không tìm thấy dữ liệu trên Google Drive.");throw new AppError(502,"Chưa thể hoàn tất thao tác với Google ("+response.status+"). Vui lòng thử lại.");}if(response.status===204)return {};return response.json()}
export async function findChild(parent:string,name:string){const q="'"+parent+"' in parents and trashed = false and name = '"+name.replaceAll("'","\\'")+"'";const data=await gapi("drive/v3/files?"+new URLSearchParams({q,fields:"files(id,name,mimeType)",pageSize:"100"}));if(data.files?.length>1)throw new AppError(409,"Có nhiều mục trùng tên "+name+". Vui lòng đổi tên mục trùng trước khi tiếp tục.");return data.files?.[0]}
export async function folder(parent:string,name:string){const existing=await findChild(parent,name);if(existing){if(existing.mimeType!=="application/vnd.google-apps.folder")throw new AppError(409,"Tên thư mục bị trùng với một tệp: "+name);return existing.id}const f=await gapi("drive/v3/files?fields=id",{method:"POST",body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",parents:[parent]})});return f.id}
async function ensureWorkbook(id:string,names:string[]){const meta=await gapi("sheets/v4/spreadsheets/"+id+"?fields=sheets.properties.title");const current=new Set((meta.sheets||[]).map((s:any)=>s.properties.title));const missing=names.filter(n=>!current.has(n));if(missing.length)await gapi("sheets/v4/spreadsheets/"+id+":batchUpdate",{method:"POST",body:JSON.stringify({requests:missing.map(title=>({addSheet:{properties:{title,gridProperties:{frozenRowCount:1,columnCount:Math.max(26,COMMON.length+TABLES[title].fields.length)}}}}))})});for(const table of names){const head=[...COMMON,...TABLES[table].fields];await gapi("sheets/v4/spreadsheets/"+id+"/values/"+encodeURIComponent(table+"!A1:Z1")+"?valueInputOption=RAW",{method:"PUT",body:JSON.stringify({values:[head]})})}}
async function makeWorkbook(parent:string,name:string,priv:boolean){let existing=await findChild(parent,name);const names=Object.keys(TABLES).filter(t=>!!TABLES[t].private===priv);if(existing){await ensureWorkbook(existing.id,names);return existing.id}
const data=await gapi("sheets/v4/spreadsheets",{method:"POST",body:JSON.stringify({properties:{title:name,locale:"vi_VN",timeZone:"Asia/Ho_Chi_Minh"},sheets:[{properties:{sheetId:0,title:"HUONG_DAN",gridProperties:{frozenRowCount:1}},data:[{rowData:[["NỘI DUNG","HƯỚNG DẪN"],["Quản lý","Mỗi dòng là một bản ghi. Không đổi tên tab hoặc hàng tiêu đề."],["Quyền xem","Chỉ quản trị viên và máy chủ được truy cập file. Thành viên sử dụng website."],["Khôi phục","status=deleted là đã gỡ. Không xóa hàng để giữ liên kết dữ liệu."],["Ảnh/video","Tệp gốc lưu trong Google Drive; TEP_MEDIA chứa mã tệp."],...names.map(n=>[n,TABLES[n].label])].map(row=>({values:row.map(v=>({userEnteredValue:{stringValue:v}}))}))}]},...names.map((n,i)=>({properties:{sheetId:i+1,title:n,gridProperties:{frozenRowCount:1,columnCount:Math.max(26,COMMON.length+TABLES[n].fields.length)}},data:[{rowData:[{values:[...COMMON,...TABLES[n].fields].map(v=>({userEnteredValue:{stringValue:v},userEnteredFormat:{backgroundColor:{red:.13,green:.3,blue:.24},textFormat:{bold:true,foregroundColor:{red:1,green:1,blue:1}},wrapStrategy:"WRAP"}}))}]}]}))]})});
const created=await gapi("drive/v3/files/"+data.spreadsheetId+"?fields=parents");await gapi("drive/v3/files/"+data.spreadsheetId+"?"+new URLSearchParams({addParents:parent,...(created.parents?.length?{removeParents:created.parents.join(",")}:{}),fields:"id,parents"}),{method:"PATCH",body:"{}"});return data.spreadsheetId}
export async function initializeDrive(){await accessToken();const root=await gapi("drive/v3/files/"+ROOT_FOLDER+"?fields=id,name,mimeType,capabilities(canAddChildren),permissions(type,role)");if(root.mimeType!=="application/vnd.google-apps.folder"||!root.capabilities?.canAddChildren)throw new AppError(403,"Tài khoản Google cần có quyền chỉnh sửa thư mục A14.");if(root.permissions?.some((p:any)=>["anyone","domain"].includes(p.type)))throw new AppError(409,"Thư mục A14 đang chia sẻ rộng. Hãy đổi Quyền truy cập chung thành Bị hạn chế trước khi khởi tạo dữ liệu riêng của lớp.");
const dataFolder=await folder(ROOT_FOLDER,"01_Du_lieu");const mediaFolder=await folder(ROOT_FOLDER,"02_Anh_Video");const thumb=await folder(ROOT_FOLDER,"03_Anh_thu_nho");const backup=await folder(ROOT_FOLDER,"04_Sao_luu");const yearFolders:Record<string,string>={};for(const y of ["Lop_10","Lop_11","Lop_12","Hop_lop","Anh_dai_dien","Chua_ro_nam"])yearFolders[y]=await folder(mediaFolder,y);
const content=await makeWorkbook(dataFolder,"A14_Noi_dung",false);const privateSheet=await makeWorkbook(dataFolder,"A14_Quan_tri_Rieng_tu",true);
await saveConfig("storage",{content,privateSheet,dataFolder,mediaFolder,thumb,backup,yearFolders,root:ROOT_FOLDER,schemaVersion:SCHEMA_VERSION,initializedAt:new Date().toISOString()});return {content,privateSheet}}
export async function storage(){const s:any=await config("storage");if(!s)throw new AppError(503,"Chưa khởi tạo các bảng dữ liệu. Quản trị viên hãy vào Kết nối Google Drive.");if(Number(s.schemaVersion||0)<SCHEMA_VERSION){if(!schemaUpgrade)schemaUpgrade=(async()=>{await ensureWorkbook(s.content,Object.keys(TABLES).filter(t=>!TABLES[t].private));await ensureWorkbook(s.privateSheet,Object.keys(TABLES).filter(t=>!!TABLES[t].private));const next={...s,schemaVersion:SCHEMA_VERSION};await saveConfig("storage",next);return next})().finally(()=>{schemaUpgrade=null});return schemaUpgrade}return s}
async function sheetId(table:string){if(!TABLES[table])throw new AppError(404,"Không có bảng dữ liệu này.");const s=await storage();return TABLES[table].private?s.privateSheet:s.content}
export async function rows(table:string):Promise<Row[]>{const id=await sheetId(table);const data=await gapi("sheets/v4/spreadsheets/"+id+"/values/"+encodeURIComponent(table+"!A1:Z"));const [head,...values]=data.values||[];if(!head)return [];return values.map((v:string[],index:number)=>Object.fromEntries([...head.map((k:string,i:number)=>[k,String(v[i]??"")]),["_row",String(index+2)]]))}
export async function append(table:string,row:Row){const id=await sheetId(table);const head=[...COMMON,...TABLES[table].fields];await gapi("sheets/v4/spreadsheets/"+id+"/values/"+encodeURIComponent(table+"!A:Z")+":append?valueInputOption=RAW&insertDataOption=INSERT_ROWS",{method:"POST",body:JSON.stringify({values:[head.map(k=>row[k]||"")]})});return row}
export async function update(table:string,row:Row){if(!/^[0-9]+$/.test(row._row||""))throw new AppError(409,"Không xác định được dòng dữ liệu.");const id=await sheetId(table);await gapi("sheets/v4/spreadsheets/"+id+"/values/"+encodeURIComponent(table+"!A"+row._row)+ "?valueInputOption=RAW",{method:"PUT",body:JSON.stringify({values:[[...COMMON,...TABLES[table].fields].map(k=>row[k]||"")]})});return row}
export function newRow(owner:string,fields:Row):Row{const now=new Date().toISOString();return {...fields,id:crypto.randomUUID(),owner_id:owner,created_at:now,updated_at:now,status:"active"}}
export async function audit(owner:string,action:string,target:string){await append("NHAT_KY",newRow(owner,{action,target_id:target}))}
export function oauthRedirect(){return setting("SITE_ORIGIN")+"/api/google/callback"}
