
import { env } from "cloudflare:workers";
export class AppError extends Error { constructor(public status:number,message:string){super(message)} }
export function setting(key:string){return (env as unknown as Record<string,string>)[key] || process.env[key] || ""}
export function database(){if(!env.DB)throw new AppError(503,"Hệ thống tài khoản đang được chuẩn bị. Vui lòng thử lại.");return env.DB}
const enc=new TextEncoder();
export function base64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"")}
export function unbase64(s:string){return Uint8Array.from(atob(s.replaceAll("-","+").replaceAll("_","/")),c=>c.charCodeAt(0))}
export function random(){return base64(crypto.getRandomValues(new Uint8Array(32)))}
function secret(){const s=setting("SESSION_SECRET");if(!s)throw new AppError(503,"Đăng nhập chưa được cấu hình.");return s}
export async function hashPassword(password:string,salt=random()){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:100000,hash:"SHA-256"},key,256);return salt+"."+base64(new Uint8Array(bits))}
export async function verifyPassword(password:string,hash:string){if(!hash)return false;const computed=await hashPassword(password,hash.split(".")[0]);let diff=hash.length^computed.length;for(let i=0;i<Math.max(hash.length,computed.length);i++)diff|=(hash.charCodeAt(i)||0)^(computed.charCodeAt(i)||0);return diff===0}
export async function sign(value:unknown){const payload=base64(enc.encode(JSON.stringify(value)));const key=await crypto.subtle.importKey("raw",enc.encode(secret()),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(payload));return payload+"."+base64(new Uint8Array(sig))}
export async function verify(token:string){try{const [p,s]=token.split(".");const key=await crypto.subtle.importKey("raw",enc.encode(secret()),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,unbase64(s),enc.encode(p)))return null;const data=JSON.parse(new TextDecoder().decode(unbase64(p)));return data.exp>Date.now()?data:null}catch{return null}}
export async function seal(value:unknown){const key=await crypto.subtle.importKey("raw",await crypto.subtle.digest("SHA-256",enc.encode(secret())),"AES-GCM",false,["encrypt"]);const iv=crypto.getRandomValues(new Uint8Array(12));const result=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(JSON.stringify(value)));return base64(iv)+"."+base64(new Uint8Array(result))}
export async function unseal(value:string){const [iv,data]=value.split(".");const key=await crypto.subtle.importKey("raw",await crypto.subtle.digest("SHA-256",enc.encode(secret())),"AES-GCM",false,["decrypt"]);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:unbase64(iv)},key,unbase64(data))))}
export async function config(key:string){const row=await database().prepare("SELECT value FROM secure_config WHERE key=?").bind(key).first<{value:string}>();return row?unseal(row.value):null}
export async function saveConfig(key:string,value:unknown){await database().prepare("INSERT INTO secure_config(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,await seal(value)).run()}
export function cookie(req:Request,name:string){return (req.headers.get("cookie")||"").split(";").map(s=>s.trim()).find(s=>s.startsWith(name+"="))?.slice(name.length+1)||""}
export function sessionCookie(req:Request,value:string,maxAge=28800){return "a14_session="+value+"; HttpOnly; "+(req.headers.get("origin")===setting("FRONTEND_ORIGIN")&&!!setting("FRONTEND_ORIGIN")?"SameSite=None":"SameSite=Lax")+"; Path=/; Max-Age="+maxAge+(new URL(req.url).protocol==="https:"?"; Secure":"")}
export type User={id:string;username:string;name:string;email?:string;role:"admin"|"member";status:string};
export async function currentUser(req:Request):Promise<User|null>{const bearer=req.headers.get("authorization")?.match(/^Bearer ([A-Za-z0-9._-]+)$/)?.[1];const session=await verify(bearer||cookie(req,"a14_session"));if(!session||session.purpose!=="session")return null;if(session.id==="admin")return {id:"admin",username:setting("ADMIN_USERNAME")||"TANNV",name:"TANNV",role:"admin",status:"active"};const u=await database().prepare("SELECT id,username,name,email,status FROM auth_users WHERE id=?").bind(session.id).first<Omit<User,"role">>();return u?{...u,role:"member"}:null}
export async function requireUser(req:Request,admin=false){const u=await currentUser(req);if(!u)throw new AppError(401,"Vui lòng đăng nhập.");if(u.status!=="active")throw new AppError(403,"Tài khoản của bạn chưa được duyệt hoặc đã bị khóa.");if(admin&&u.role!=="admin")throw new AppError(403,"Chỉ quản trị viên được thực hiện thao tác này.");return u}
export function sameOrigin(req:Request){const origin=req.headers.get("origin");const expected=setting("SITE_ORIGIN")||new URL(req.url).origin;if(!origin||(origin!==expected&&origin!==setting("FRONTEND_ORIGIN")))throw new AppError(403,"Yêu cầu không hợp lệ. Vui lòng tải lại trang.")}
export async function limit(req:Request,action:string,max=12){const ip=req.headers.get("cf-connecting-ip")||"local";const now=Date.now();const key=action+":"+base64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(ip))))+":"+Math.floor(now/900000);const row=await database().prepare("INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count").bind(key,now+900000).first<{count:number}>();if((row?.count||0)>max)throw new AppError(429,"Bạn thao tác quá nhiều lần. Vui lòng thử lại sau 15 phút.")}
export function validText(value:unknown,label:string,max=5000,required=true){if(typeof value!=="string"||(required&&!value.trim())||value.length>max)throw new AppError(400,label+" không hợp lệ.");return value.trim()}
